#!/bin/sh
export KUBECONFIG="/root/.kube/config"
action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME 
mychart=/cnab/app/charts/alpine
greeting=${CNAB_P_GREETING:-"Hi"}
ns=${CNAB_P_NAMESPACE:-"vote"}

echo "[== $greeting Duffle user ==]"
case $action in
    install)
        echo "Installing local chart"
        helm install --namespace $ns -n $name $mychart
        ;;
    uninstall)
        echo "uninstall action"
        helm delete --purge $name
        ;;
    upgrade)
        echo "Upgrade action"
        helm upgrade --namespace $ns $name $mychart
        ;;
    status)
        echo "Status action"
        helm history $name
        helm status $name
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
