CNAB_ACTION ?= "status"

install:
	@echo "Do Install"
	@echo $(CNAB_ACTION)

uninstall: 
	@echo "Do Uninstall"

upgrade:
	@echo "Do Upgrade"

status:
	@echo "Do Status"

.PHONY: install uninstall upgrade status