#!/bin/sh
set -e

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME
mychart="stable/wordpress"
greeting=${CNAB_P_GREETING:-"Hi! Let's make provisioning a mysql service and installing wordpress on AKS even easier!"}

echo "[== $greeting Duffle user ==]"
case $action in
    install)
        echo "This installation assumes you already have an AKS cluster"
        echo "Grabbing kubeconfig for cluster $CNAB_P_CLUSTER_NAME in resource group: $CNAB_P_RESOURCE_GROUP"
        az aks get-credentials --resource-group $CNAB_P_RESOURCE_GROUP --name $CNAB_P_CLUSTER_NAME

        echo "Configuring helm to easily install apps on your AKS cluster..."
        helm init --client-only


        echo "Creating a resource group called $CNAB_P_MYSQL_RESOURCE_GROUP for the mysql database service..."
        az group create --name $CNAB_P_MYSQL_RESOURCE_GROUP --location westus

        echo "Creating a managed mysql database server..."
        az mysql server create --resource-group $CNAB_P_MYSQL_RESOURCE_GROUP --name $CNAB_P_MYSQL_DB_SERVICE_NAME  --location westus --admin-user $MYSQL_USER --admin-password $MYSQL_PASSWORD --sku-name GP_Gen4_2 --version 5.7

        echo "Creating a database called bitnami_wordpress on your mysql database server..."
        az mysql db create --name bitnami_wordpress --resource-group $CNAB_P_MYSQL_RESOURCE_GROUP --server-name=$CNAB_P_MYSQL_DB_SERVICE_NAME

        # Allow Azure IPs to access this db service
        az mysql server firewall-rule create --resource-group $CNAB_P_MYSQL_RESOURCE_GROUP --server $CNAB_P_MYSQL_DB_SERVICE_NAME --name "AllowAllWindowsAzureIps" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0

        mysql_host="$CNAB_P_MYSQL_DB_SERVICE_NAME.mysql.database.azure.com"
        echo "Installing remote chart with connection to Azure MySQL..."
        helm install -n $name $mychart --set externalDatabase.host=$mysql_host,externalDatabase.user=$MYSQL_USER,externalDatabase.password=$MYSQL_PASSWORD,mariadb.enabled=false

        echo "Congratulations! Enjoy your new wordpress application running on AKS and connected to your newly provisioned mysql instance on Azure!"

        ;;
    uninstall)
        echo "uninstall action"
        helm delete --purge $name
        az group delete $CNAB_P_MYSQL_RESOURCE_GROUP
        ;;
    upgrade)
        echo "Upgrade action"
        helm upgrade $name $mychart
        ;;
    status)
        echo "Status action"
        helm status $name
        #TODO: check on mysql instance health
        ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
