#!/bin/sh

#set -eo pipefail

action=$CNAB_ACTION
name=$CNAB_INSTALLATION_NAME 

echo "Port parameter was set to ${PORT}"
case $action in
    install)
    echo "Install action"
    ;;
    uninstall)
    echo "Uninstall action"
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    downgrade)
    echo "Downgrade action"
    ;;
    status)
    echo "Status action"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
